name: prolog

# Add other packages you are using here
dependencies:
- base >= 4.9 && < 5
- hlint-source-plugin

ghc-options:
- -Werror                   # warnings are errors
- -Wincomplete-patterns     # cover all cases!
- -Wunused-binds            # use all your bindings
- -Wunused-matches          # use all your pattern matches!
- -Wmissing-signatures      # write all your toplevel signatures!
- -Wname-shadowing          # use different names!
- -Wincomplete-uni-patterns # warn about incomplete patterns v2
- -fplugin=HLint            # run hlint on compilation

library:
  source-dirs: src

extra-source-files: # so we also track .hlint.yaml for changes
- .hlint.yaml

executables:
  prolog:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prolog
